name: ios-ci
on:
  pull_request:
    branches: [ main ]
    paths:
      - "mobiles/ios/**"

jobs:
  ios-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "iOS CI OK"
